# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=1000, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Content', verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Content', verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('credit', models.PositiveIntegerField(verbose_name='credit')),
                ('description', models.CharField(default='', max_length=1000, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Content', verbose_name='content')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Course', verbose_name='course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Course', verbose_name='course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Course', verbose_name='course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Course', verbose_name='course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Course', verbose_name='course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTeachingAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Course', verbose_name='course')),
                ('teaching_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User', verbose_name='teaching assistant')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='score')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('description', models.CharField(default='', max_length=1000, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='ExamContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Content', verbose_name='content')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Exam', verbose_name='exam')),
            ],
        ),
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='score')),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('description', models.CharField(default='', max_length=1000, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='ExcerciseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Content', verbose_name='content')),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Excercise', verbose_name='excercise')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='contents/', verbose_name='file')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('description', models.CharField(default='', max_length=1000, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('description', models.CharField(default='', max_length=1000, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Content', verbose_name='content')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Notification', verbose_name='notification')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='score')),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('description', models.CharField(default='', max_length=1000, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Content', verbose_name='content')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Project', verbose_name='project')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('description', models.CharField(default='', max_length=1000, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='score')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Exam', verbose_name='exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User', verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='UserExcercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='score')),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Excercise', verbose_name='excercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User', verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='score')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Project', verbose_name='project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User', verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='contents',
            field=models.ManyToManyField(through='visage.ProjectContent', to='visage.Content', verbose_name='contents'),
        ),
        migrations.AddField(
            model_name='notification',
            name='contents',
            field=models.ManyToManyField(through='visage.NotificationContent', to='visage.Content', verbose_name='contents'),
        ),
        migrations.AddField(
            model_name='notification',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User', verbose_name='poster'),
        ),
        migrations.AddField(
            model_name='excercise',
            name='contents',
            field=models.ManyToManyField(through='visage.ExcerciseContent', to='visage.Content', verbose_name='contents'),
        ),
        migrations.AddField(
            model_name='exam',
            name='contents',
            field=models.ManyToManyField(through='visage.ExamContent', to='visage.Content', verbose_name='contents'),
        ),
        migrations.AddField(
            model_name='courseproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='coursenotification',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Notification', verbose_name='notification'),
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='excercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Excercise', verbose_name='excercise'),
        ),
        migrations.AddField(
            model_name='courseexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Exam', verbose_name='exam'),
        ),
        migrations.AddField(
            model_name='course',
            name='contents',
            field=models.ManyToManyField(through='visage.CourseContent', to='visage.Content', verbose_name='contents'),
        ),
        migrations.AddField(
            model_name='course',
            name='exams',
            field=models.ManyToManyField(through='visage.CourseExam', to='visage.Exam', verbose_name='exams'),
        ),
        migrations.AddField(
            model_name='course',
            name='exercises',
            field=models.ManyToManyField(through='visage.CourseExercise', to='visage.Excercise', verbose_name='exercises'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User', verbose_name='instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='notifications',
            field=models.ManyToManyField(through='visage.CourseNotification', to='visage.Notification', verbose_name='notifications'),
        ),
        migrations.AddField(
            model_name='course',
            name='projects',
            field=models.ManyToManyField(through='visage.CourseProject', to='visage.Project', verbose_name='projects'),
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_assistants',
            field=models.ManyToManyField(related_name='ta_course_set', through='visage.CourseTeachingAssistant', to='authentication.User', verbose_name='teachingassistants'),
        ),
        migrations.AddField(
            model_name='contenttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.Tag', verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='contentfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visage.File', verbose_name='file'),
        ),
        migrations.AddField(
            model_name='content',
            name='files',
            field=models.ManyToManyField(through='visage.ContentFile', to='visage.File', verbose_name='files'),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(through='visage.ContentTag', to='visage.Tag', verbose_name='tags'),
        ),
    ]
