# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visage', '0002_auto_20170627_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'content', 'verbose_name_plural': 'contents'},
        ),
        migrations.AlterModelOptions(
            name='contentfile',
            options={'verbose_name': 'content file', 'verbose_name_plural': 'content files'},
        ),
        migrations.AlterModelOptions(
            name='contenttag',
            options={'verbose_name': 'content tag', 'verbose_name_plural': 'content tags'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'verbose_name': 'course content', 'verbose_name_plural': 'course contents'},
        ),
        migrations.AlterModelOptions(
            name='courseexam',
            options={'verbose_name': 'course exam', 'verbose_name_plural': 'course exams'},
        ),
        migrations.AlterModelOptions(
            name='courseexercise',
            options={'verbose_name': 'course excercise', 'verbose_name_plural': 'course excercises'},
        ),
        migrations.AlterModelOptions(
            name='coursenotification',
            options={'verbose_name': 'course notification', 'verbose_name_plural': 'course notifications'},
        ),
        migrations.AlterModelOptions(
            name='courseproject',
            options={'verbose_name': 'course project', 'verbose_name_plural': 'course projects'},
        ),
        migrations.AlterModelOptions(
            name='courseteachingassistant',
            options={'verbose_name': 'course teaching assistant', 'verbose_name_plural': 'course teaching assistants'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'exam', 'verbose_name_plural': 'exams'},
        ),
        migrations.AlterModelOptions(
            name='examcontent',
            options={'verbose_name': 'exam content', 'verbose_name_plural': 'exam contents'},
        ),
        migrations.AlterModelOptions(
            name='excercise',
            options={'verbose_name': 'excercise', 'verbose_name_plural': 'excercises'},
        ),
        migrations.AlterModelOptions(
            name='excercisecontent',
            options={'verbose_name': 'excercise content', 'verbose_name_plural': 'excercise contents'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterModelOptions(
            name='notificationcontent',
            options={'verbose_name': 'notification content', 'verbose_name_plural': 'notification contents'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectcontent',
            options={'verbose_name': 'project content', 'verbose_name_plural': 'project contents'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='userexam',
            options={'verbose_name': 'user exam', 'verbose_name_plural': 'user exams'},
        ),
        migrations.AlterModelOptions(
            name='userexcercise',
            options={'verbose_name': 'user excercise', 'verbose_name_plural': 'user excercises'},
        ),
        migrations.AlterModelOptions(
            name='userproject',
            options={'verbose_name': 'user project', 'verbose_name_plural': 'user projects'},
        ),
    ]
