# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(null=True, upload_to='profile_photos/', verbose_name='profile photo')),
                ('student_number', models.CharField(max_length=10, null=True, verbose_name='student number')),
                ('entry_date', models.DateField(null=True, verbose_name='entry date')),
                ('type', models.CharField(choices=[('S', 'Student'), ('I', 'Instructor'), ('T', 'Teaching Assistant')], default='S', max_length=1, verbose_name='type')),
                ('sex', models.CharField(choices=[('S', 'Student'), ('I', 'Instructor'), ('T', 'Teaching Assistant')], default='M', max_length=1, verbose_name='sex')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='score')),
                ('state', models.CharField(choices=[('U', 'Unknown'), ('P', 'Pass'), ('F', 'Fail'), ('A', 'Abscense'), ('R', 'Removal')], default='U', max_length=1, verbose_name='state')),
            ],
        ),
    ]
